name: CI
on:
  workflow_call:
    secrets:
      gcp_keyfile:
        required: true
      localstack_api_key:
        required: true
    
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GCP_KEYFILE: ${{ secrets.GCP_KEYFILE }}
      LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version 1.6.1
      - name: Install Python Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Run dbt deps
        run: |
          cd ./integration_tests
          dbt deps
      - name: dbt CI - duckdb - with stream
        run: |
          cd ./integration_tests
          sed -i 's/skip_stream: true/skip_stream: false/' dbt_project.yml
          dbt build -x --target duckdb
        env:
          GCP_KEYFILE_PATH: ./gcp_keyfile.json
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml
      - name: dbt CI - duckdb - skip stream
        run: |
          cd ./integration_tests
          sed -i 's/skip_stream: false/skip_stream: true/' dbt_project.yml
          dbt build -x --target duckdb
        env:
          GCP_KEYFILE_PATH: ./gcp_keyfile.json
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml
      - name: dbt CI - snowflake - with stream
        id: snowflake_ci_with_stream
        if: github.repository == 'bcodell/dbt-activity-schema'
        run: |
          localstack extensions install localstack-extension-snowflake
          localstack start -d
          cd ./integration_tests
          sed -i 's/skip_stream: true/skip_stream: false/' dbt_project.yml
          dbt build -x --target snowflake --exclude dataset__select_all_aggregate_all
        env:
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml
          DEBUG: 1

      - name: dbt CI - snowflake - skip stream
        id: snowflake_ci_skip_stream
        if: github.repository == 'bcodell/dbt-activity-schema'
        run: |
          cd ./integration_tests
          sed -i 's/skip_stream: false/skip_stream: true/' dbt_project.yml
          dbt run -s activities+ -x --target snowflake --exclude dataset__select_all_aggregate_all
          dbt test -s activities+ -x --target snowflake --exclude dataset__select_all_aggregate_all
        env:
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml
          DEBUG: 1
      - name: localstack logs
        if: failure() && (steps.snowflake_ci_with_stream.outcome == 'failure' || steps.snowflake_ci_skip_stream.outcome == 'failure' )
        run: localstack logs
      - name: dbt CI - bigquery - with stream
        if: github.repository == 'bcodell/dbt-activity-schema'
        run: |
          cd ./integration_tests
          sed -i 's/skip_stream: true/skip_stream: false/' dbt_project.yml
          echo $GCP_KEYFILE > $GCP_KEYFILE_PATH
          ls -l
          dbt build -x --target bigquery
        env:
          GCP_KEYFILE_PATH: ./gcp_keyfile.json
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml
      - name: dbt CI - bigquery - skip stream
        if: github.repository == 'bcodell/dbt-activity-schema'
        run: |
          cd ./integration_tests
          sed -i 's/skip_stream: false/skip_stream: true/' dbt_project.yml
          echo $GCP_KEYFILE > $GCP_KEYFILE_PATH
          ls -l
          dbt run -s activities+ -x --target bigquery
          dbt test -s activities+ -x --target bigquery
        env:
          GCP_KEYFILE_PATH: ./gcp_keyfile.json
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml

